# ---------------------------------------
# 1. FRONTEND Stage — Vite + Node 22
# ---------------------------------------
FROM node:22 AS frontend
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# ---------------------------------------
# 2. BACKEND Stage — PHP 8.3 + Laravel
# ---------------------------------------
FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git zip unzip libpq-dev \
    libpng-dev libjpeg62-turbo-dev libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql gd \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

# копируем собранный фронтенд
COPY --from=frontend /app/dist ./public/build

RUN composer install --no-dev --optimize-autoloader \
    && php artisan route:clear \
    && php artisan config:clear \
    && php artisan view:clear \
    && chmod -R 777 storage bootstrap/cache

CMD ["php-fpm"]
