package dto

import (
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/almukha/compnet-backend/internal/domain/chat"
)

var uuidPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// StartChatSessionRequest is the optional POST /api/v1/chat/session body.
type StartChatSessionRequest struct {
	// PageURL is the page the visitor started the chat from.
	PageURL string `json:"page_url"`
}

// SendChatMessageRequest is the POST /api/v1/chat/messages body.
type SendChatMessageRequest struct {
	// ClientMessageID is generated by the browser per message and reused on
	// retry, so a resend after a network error never creates a duplicate.
	// It only deduplicates within the cookie's conversation and never grants
	// access to anything.
	ClientMessageID string `json:"client_message_id"`
	Body            string `json:"body"`
	// Website is a honeypot: the real widget never fills it, bots often do.
	Website string `json:"website"`
}

// NormalizedChatBody trims surrounding whitespace and unifies line endings.
func NormalizedChatBody(raw string) string {
	return strings.TrimSpace(strings.ReplaceAll(raw, "\r\n", "\n"))
}

// Validate checks the message body and client id. Lengths are counted in
// characters, matching the char_length() CHECK in the database.
func (r SendChatMessageRequest) Validate() map[string]string {
	fields := map[string]string{}

	if !uuidPattern.MatchString(strings.TrimSpace(r.ClientMessageID)) {
		fields["client_message_id"] = "нужен UUID"
	}

	body := NormalizedChatBody(r.Body)
	switch {
	case body == "":
		fields["body"] = "сообщение не может быть пустым"
	case !utf8.ValidString(body) || strings.ContainsRune(body, 0):
		fields["body"] = "недопустимые символы"
	case utf8.RuneCountInString(body) > chat.MaxBodyLength:
		fields["body"] = "сообщение длиннее 2000 символов"
	}

	return fields
}

// MarkChatReadRequest is the POST /api/v1/chat/read body.
type MarkChatReadRequest struct {
	LastMessageID int64 `json:"last_message_id"`
}

// Validate checks that the id is a plausible message id.
func (r MarkChatReadRequest) Validate() map[string]string {
	fields := map[string]string{}
	if r.LastMessageID <= 0 {
		fields["last_message_id"] = "нужен id сообщения"
	}
	return fields
}

// UpdateChatContactRequest is the PUT /api/v1/chat/contact body.
type UpdateChatContactRequest struct {
	Name    string `json:"name"`
	Contact string `json:"contact"`
}

// Validate requires a contact (phone, email or messenger handle) and limits
// both fields' length.
func (r UpdateChatContactRequest) Validate() map[string]string {
	fields := map[string]string{}

	name := strings.TrimSpace(r.Name)
	if !utf8.ValidString(name) || strings.ContainsRune(name, 0) {
		fields["name"] = "недопустимые символы"
	} else if utf8.RuneCountInString(name) > chat.MaxVisitorNameLength {
		fields["name"] = "слишком длинное имя"
	}

	contact := strings.TrimSpace(r.Contact)
	switch {
	case contact == "":
		fields["contact"] = "укажите телефон, email или мессенджер"
	case !utf8.ValidString(contact) || strings.ContainsRune(contact, 0):
		fields["contact"] = "недопустимые символы"
	case utf8.RuneCountInString(contact) > chat.MaxContactLength:
		fields["contact"] = "слишком длинное значение"
	}

	return fields
}

// ChatMessageResponse is one message as the visitor sees it. Staff identity
// is deliberately not exposed.
type ChatMessageResponse struct {
	ID              int64     `json:"id"`
	Author          string    `json:"author"`
	Body            string    `json:"body"`
	ClientMessageID string    `json:"client_message_id,omitempty"`
	CreatedAt       time.Time `json:"created_at"`
}

// NewChatMessageResponse builds the visitor view of a message. The client
// id is only echoed for the visitor's own messages, so the widget can match
// a pending bubble to its saved version.
func NewChatMessageResponse(m chat.Message) ChatMessageResponse {
	resp := ChatMessageResponse{
		ID:        m.ID,
		Author:    string(m.Author),
		Body:      m.Body,
		CreatedAt: m.CreatedAt,
	}
	if m.Author == chat.AuthorVisitor {
		resp.ClientMessageID = m.ClientMessageID
	}
	return resp
}

// NewChatMessageListResponse maps a slice, never returning null.
func NewChatMessageListResponse(items []chat.Message) []ChatMessageResponse {
	result := make([]ChatMessageResponse, 0, len(items))
	for _, item := range items {
		result = append(result, NewChatMessageResponse(item))
	}
	return result
}

// ChatConversationResponse is the GET /api/v1/chat payload. The internal
// conversation id is not exposed: the cookie is the only handle a visitor
// needs.
type ChatConversationResponse struct {
	Status         string    `json:"status"`
	VisitorName    string    `json:"visitor_name"`
	VisitorContact string    `json:"visitor_contact"`
	LastMessageID  int64     `json:"last_message_id"`
	LastReadID     int64     `json:"last_read_id"`
	UnreadCount    int       `json:"unread_count"`
	CreatedAt      time.Time `json:"created_at"`
}

// NewChatConversationResponse builds the visitor view of a conversation.
func NewChatConversationResponse(c chat.Conversation) ChatConversationResponse {
	return ChatConversationResponse{
		Status:         string(c.Status),
		VisitorName:    c.VisitorName,
		VisitorContact: c.VisitorContact,
		LastMessageID:  c.LastMessageID,
		LastReadID:     c.VisitorLastReadID,
		UnreadCount:    c.UnreadForVisitor,
		CreatedAt:      c.CreatedAt,
	}
}
